# CMake generated Testfile for 
# Source directory: /home/ubuntu/primefusion-project/ns3/ns-allinone-3.41/ns-3.41/examples/energy
# Build directory: /home/ubuntu/primefusion-project/ns3/ns-allinone-3.41/ns-3.41/cmake-cache/examples/energy
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ctest-energy-model-example "ns3.41-energy-model-example-default")
set_tests_properties(ctest-energy-model-example PROPERTIES  WORKING_DIRECTORY "/home/ubuntu/primefusion-project/ns3/ns-allinone-3.41/ns-3.41/build/examples/energy/" _BACKTRACE_TRIPLES "/home/ubuntu/primefusion-project/ns3/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/ubuntu/primefusion-project/ns3/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;122;set_runtime_outputdirectory;/home/ubuntu/primefusion-project/ns3/ns-allinone-3.41/ns-3.41/build-support/macros-and-definitions.cmake;1392;build_exec;/home/ubuntu/primefusion-project/ns3/ns-allinone-3.41/ns-3.41/examples/energy/CMakeLists.txt;1;build_example;/home/ubuntu/primefusion-project/ns3/ns-allinone-3.41/ns-3.41/examples/energy/CMakeLists.txt;0;")
add_test(ctest-energy-model-with-harvesting-example "ns3.41-energy-model-with-harvesting-example-default")
set_tests_properties(ctest-energy-model-with-harvesting-example PROPERTIES  WORKING_DIRECTORY "/home/ubuntu/primefusion-project/ns3/ns-allinone-3.41/ns-3.41/build/examples/energy/" _BACKTRACE_TRIPLES "/home/ubuntu/primefusion-project/ns3/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/ubuntu/primefusion-project/ns3/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;122;set_runtime_outputdirectory;/home/ubuntu/primefusion-project/ns3/ns-allinone-3.41/ns-3.41/build-support/macros-and-definitions.cmake;1392;build_exec;/home/ubuntu/primefusion-project/ns3/ns-allinone-3.41/ns-3.41/examples/energy/CMakeLists.txt;13;build_example;/home/ubuntu/primefusion-project/ns3/ns-allinone-3.41/ns-3.41/examples/energy/CMakeLists.txt;0;")
